sudo: required
services:
  - docker

before_install:
  - docker build -t shaifal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaifal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "lasticbeanstalk-us-west-2"
  bucket_path: "docker"
  on:
    branch: master